alias clear="tput reset"
alias show="tput reset; ls -a"
alias cnrs="tput reset; npm run start"
alias nrs="npm run start"
alias clg="TASKKILL //F //IM 'League of Legends.exe' //IM 'LeagueClient.exe'"
alias leave="TASKKILL //F //IM 'code.exe'"
alias e="exit";
alias ncommit="git commit -a --allow-empty-message -m ''"
alias pall="git add .; ncommit; git push"
alias bashrc="source ~/.bashrc; cat ~/.bashrc;"
alias webcrawl="echo 'wget --spider --recursive --no-verbose --output-file=urls.txt http://example.com'"
